### DISCUSSION TITLE
GitHub Action to install NVC

### DISCUSSION THREAD

**Discussion by nickg** [nickg/nvc#920] [Announcements]
https://github.com/marketplace/actions/setup-nvc

You can use it in a GitHub Actions workflow like this:

```yaml
- uses: nickg/setup-nvc-ci@v1
  with:
    version: latest
- run: |
    nvc --version    # NVC binary added to path
```

There are some problems with the MSYS2 shell in Windows which I am still investigating. Ubuntu and Powershell work fine.
